// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq6sT3vFfckcWQ8BhFJ9DrZM5pTfD235o',
    appId: '1:588972166346:web:965ea58e5cb5ea2f727833',
    messagingSenderId: '588972166346',
    projectId: 'not-working-4d559',
    authDomain: 'not-working-4d559.firebaseapp.com',
    storageBucket: 'not-working-4d559.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB45po_g-TKw1AS7HwiIbKVWuwhFzpYi2E',
    appId: '1:588972166346:android:a0f53b9c38cbfa7c727833',
    messagingSenderId: '588972166346',
    projectId: 'not-working-4d559',
    storageBucket: 'not-working-4d559.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChPcQ-i3Zcry5xBRuoC1J89_DSe4z6Mls',
    appId: '1:588972166346:ios:345316850e250f82727833',
    messagingSenderId: '588972166346',
    projectId: 'not-working-4d559',
    storageBucket: 'not-working-4d559.appspot.com',
    iosClientId: '588972166346-o40u5vtoppt537kmmleag59qf7pbjdtl.apps.googleusercontent.com',
    iosBundleId: 'com.example.search',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChPcQ-i3Zcry5xBRuoC1J89_DSe4z6Mls',
    appId: '1:588972166346:ios:345316850e250f82727833',
    messagingSenderId: '588972166346',
    projectId: 'not-working-4d559',
    storageBucket: 'not-working-4d559.appspot.com',
    iosClientId: '588972166346-o40u5vtoppt537kmmleag59qf7pbjdtl.apps.googleusercontent.com',
    iosBundleId: 'com.example.search',
  );
}
